# Generated by Django 5.0.2 on 2025-08-13 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advogado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("oab", models.CharField(max_length=20, unique=True)),
                ("uf_oab", models.CharField(max_length=2)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("endereco", models.TextField()),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=10)),
                ("especialidades", models.CharField(max_length=200)),
                ("data_inscricao_oab", models.DateField()),
                ("experiencia_anos", models.PositiveIntegerField()),
                ("situacao", models.CharField(default="ativo", max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Advogado",
                "verbose_name_plural": "Advogados",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="AtendimentoJuridico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("associado", models.CharField(max_length=200)),
                ("tipo_demanda", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("status", models.CharField(default="em_andamento", max_length=25)),
                ("prioridade", models.CharField(default="media", max_length=20)),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_limite", models.DateField(blank=True, null=True)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("resultado", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "advogado_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casos_responsavel",
                        to="assejus.advogado",
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento Juridico",
                "verbose_name_plural": "Atendimentos Juridicos",
                "ordering": ["-data_abertura"],
            },
        ),
        migrations.CreateModel(
            name="Andamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_andamento", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="andamentos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="andamentos",
                        to="assejus.atendimentojuridico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Andamento",
                "verbose_name_plural": "Andamentos",
                "ordering": ["-data_andamento"],
            },
        ),
        migrations.CreateModel(
            name="ConsultaJuridica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("associado", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=20)),
                ("pergunta", models.TextField()),
                ("resposta", models.TextField(blank=True)),
                ("data_consulta", models.DateTimeField(auto_now_add=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                ("resolvida", models.BooleanField(default=False)),
                (
                    "usuario_resposta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_respondidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Juridica",
                "verbose_name_plural": "Consultas Juridicas",
                "ordering": ["-data_consulta"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoJuridico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("arquivo", models.FileField(upload_to="assejus/documentos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="assejus.atendimentojuridico",
                    ),
                ),
                (
                    "usuario_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_upload",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Juridico",
                "verbose_name_plural": "Documentos Juridicos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioJuridico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fim", models.DateField()),
                ("arquivo", models.FileField(upload_to="assejus/relatorios/")),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_geracao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatorio Juridico",
                "verbose_name_plural": "Relatorios Juridicos",
                "ordering": ["-data_geracao"],
            },
        ),
    ]
