# Generated by Django 5.0.2 on 2025-08-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0001_initial"),
        ("associados", "0005_alter_associado_posto_graduacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendimentojuridico",
            name="associado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendimentos_juridicos",
                to="associados.associado",
                verbose_name="Associado",
            ),
        ),
        migrations.AlterField(
            model_name="atendimentojuridico",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                    ("critica", "Crítica"),
                ],
                default="media",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="atendimentojuridico",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("em_analise", "Em Análise"),
                    ("em_andamento", "Em Andamento"),
                    ("aguardando_documentos", "Aguardando Documentos"),
                    ("aguardando_decisao", "Aguardando Decisão"),
                    ("suspenso", "Suspenso"),
                    ("concluido", "Concluído"),
                    ("arquivado", "Arquivado"),
                    ("cancelado", "Cancelado"),
                ],
                default="aberto",
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="atendimentojuridico",
            name="tipo_demanda",
            field=models.CharField(
                choices=[
                    ("civil", "Civil"),
                    ("trabalhista", "Trabalhista"),
                    ("previdenciario", "Previdenciário"),
                    ("penal", "Penal"),
                    ("administrativo", "Administrativo"),
                    ("tributario", "Tributário"),
                    ("ambiental", "Ambiental"),
                    ("consumidor", "Consumidor"),
                    ("familia", "Família"),
                    ("sucessoes", "Sucessões"),
                    ("contratos", "Contratos"),
                    ("propriedade", "Propriedade"),
                    ("outros", "Outros"),
                ],
                max_length=20,
                verbose_name="Tipo de Demanda",
            ),
        ),
        migrations.AlterField(
            model_name="consultajuridica",
            name="associado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas_juridicas",
                to="associados.associado",
                verbose_name="Associado",
            ),
        ),
        migrations.AlterField(
            model_name="consultajuridica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("duvida_juridica", "Dúvida Jurídica"),
                    ("orientacao_legal", "Orientação Legal"),
                    ("analise_documento", "Análise de Documento"),
                    ("consulta_processo", "Consulta de Processo"),
                    ("orientacao_trabalhista", "Orientação Trabalhista"),
                    ("orientacao_previdenciaria", "Orientação Previdenciária"),
                    ("orientacao_civil", "Orientação Civil"),
                    ("outros", "Outros"),
                ],
                max_length=30,
                verbose_name="Tipo de Consulta",
            ),
        ),
        migrations.AlterField(
            model_name="documentojuridico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("peticao", "Petição"),
                    ("contrato", "Contrato"),
                    ("procuração", "Procuração"),
                    ("documento_identidade", "Documento de Identidade"),
                    ("comprovante", "Comprovante"),
                    ("laudo", "Laudo"),
                    ("parecer", "Parecer"),
                    ("sentenca", "Sentença"),
                    ("acordao", "Acórdão"),
                    ("outros", "Outros"),
                ],
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
