# Generated by Django 5.0.2 on 2025-08-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0002_alter_atendimentojuridico_associado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultajuridica",
            name="advogado_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas_responsavel",
                to="assejus.advogado",
                verbose_name="Advogado Responsável",
            ),
        ),
        migrations.AddField(
            model_name="consultajuridica",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="consultajuridica",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("respondida", "Respondida"),
                    ("arquivada", "Arquivada"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
