# Generated by Django 5.0.2 on 2025-08-18 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0003_consultajuridica_advogado_responsavel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriojuridico",
            name="arquivo",
        ),
        migrations.AddField(
            model_name="relatoriojuridico",
            name="advogado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relatorios_por_advogado",
                to="assejus.advogado",
                verbose_name="Advogado Específico",
            ),
        ),
        migrations.AddField(
            model_name="relatoriojuridico",
            name="escopo",
            field=models.CharField(
                choices=[
                    ("total", "Total Geral"),
                    ("por_advogado", "Por Advogado Específico"),
                ],
                default="total",
                max_length=20,
                verbose_name="Escopo do Relatório",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriojuridico",
            name="data_geracao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Geração"
            ),
        ),
        migrations.AlterField(
            model_name="relatoriojuridico",
            name="periodo_fim",
            field=models.DateField(verbose_name="Data de Fim"),
        ),
        migrations.AlterField(
            model_name="relatoriojuridico",
            name="periodo_inicio",
            field=models.DateField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="relatoriojuridico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mensal", "Mensal"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                    ("especial", "Especial"),
                    ("outros", "Outros"),
                ],
                max_length=30,
                verbose_name="Tipo de Relatório",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriojuridico",
            name="usuario_geracao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relatorios_gerados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário de Geração",
            ),
        ),
    ]
