# Generated by Django 5.0.2 on 2025-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0004_remove_relatoriojuridico_arquivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advogado",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="assejus/advogados/fotos/",
                verbose_name="Foto",
            ),
        ),
    ]
