# Generated by Django 5.0.2 on 2025-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0005_add_foto_advogado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advogado",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("suspenso", "Suspenso"),
                    ("aposentado", "Aposentado"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
