# Generated by Django 5.0.2 on 2025-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0006_alter_advogado_situacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="atendimentojuridico",
            name="comarca",
            field=models.CharField(
                blank=True,
                help_text="Comarca onde tramita o processo (opcional)",
                max_length=100,
                null=True,
                verbose_name="Comarca",
            ),
        ),
        migrations.AddField(
            model_name="atendimentojuridico",
            name="numero_processo",
            field=models.CharField(
                blank=True,
                help_text="Número do processo judicial (opcional)",
                max_length=50,
                null=True,
                verbose_name="Número do Processo",
            ),
        ),
        migrations.AddField(
            model_name="atendimentojuridico",
            name="vara",
            field=models.CharField(
                blank=True,
                help_text="Vara judicial específica (opcional)",
                max_length=100,
                null=True,
                verbose_name="Vara",
            ),
        ),
        migrations.AlterField(
            model_name="advogado",
            name="especialidades",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
