# Generated by Django 5.0.2 on 2025-09-01 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0007_atendimentojuridico_comarca_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advogado",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advogado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Sistema",
            ),
        ),
    ]
