# Generated by Django 5.0.2 on 2025-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0008_advogado_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="andamento",
            name="acoes_necessarias",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ações Necessárias"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="acoes_necessarias_decisao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ações Necessárias"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="assunto_contato",
            field=models.TextField(
                blank=True, null=True, verbose_name="Assunto do Contato"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="conteudo_principal",
            field=models.TextField(
                blank=True, null=True, verbose_name="Conteúdo Principal"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="conteudo_relevante",
            field=models.TextField(
                blank=True, null=True, verbose_name="Conteúdo Relevante"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="data_audiencia",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data e Hora da Audiência"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="data_decisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Decisão"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="data_recebimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Recebimento"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="decisoes_tomadas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Decisões Tomadas"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="forma_contato",
            field=models.CharField(
                blank=True,
                help_text="Ex: Telefone, Email, Presencial, etc.",
                max_length=100,
                null=True,
                verbose_name="Forma de Contato",
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="impacto_caso",
            field=models.TextField(
                blank=True, null=True, verbose_name="Impacto no Caso"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="juiz_audiencia",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Juiz"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="local_audiencia",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Local da Audiência"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="proximas_audiencias",
            field=models.TextField(
                blank=True, null=True, verbose_name="Próximas Audiências"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="proximos_passos_contato",
            field=models.TextField(
                blank=True, null=True, verbose_name="Próximos Passos"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="tipo_andamento",
            field=models.CharField(
                choices=[
                    ("contato", "Contato"),
                    ("documento", "Documento"),
                    ("audiencia", "Audiência"),
                    ("decisao", "Decisão"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
                verbose_name="Tipo de Andamento",
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="tipo_decisao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Decisão"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="tipo_documento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Documento"
            ),
        ),
    ]
