# Generated by Django 5.0.2 on 2025-09-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associados', '0001_initial'),
        ("assejus", "0009_andamento_acoes_necessarias_and_more"),
    ]

    operations = [
        # Criar modelo ProcessoJuridico
        migrations.CreateModel(
            name='ProcessoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(help_text='Ex: 0001234-56.2024.8.26.0001', max_length=50, unique=True, verbose_name='Número do Processo')),
                ('vara_tribunal', models.CharField(max_length=200, verbose_name='Vara/Tribunal')),
                ('tipo_acao', models.CharField(choices=[('civil', 'Ação Civil'), ('trabalhista', 'Ação Trabalhista'), ('previdenciaria', 'Ação Previdenciária'), ('criminal', 'Ação Criminal'), ('administrativa', 'Ação Administrativa'), ('familiar', 'Ação de Família'), ('sucessao', 'Inventário e Sucessão'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Ação')),
                ('parte_contraria', models.CharField(max_length=200, verbose_name='Parte Contrária')),
                ('situacao_atual', models.CharField(choices=[('andamento', 'Em Andamento'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado'), ('transitado_julgado', 'Transitado em Julgado'), ('concluido', 'Concluído')], default='andamento', max_length=20, verbose_name='Situação Atual')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável')),
                ('parte_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_como_cliente', to='associados.associado', verbose_name='Parte Cliente')),
            ],
            options={
                'verbose_name': 'Processo Jurídico',
                'verbose_name_plural': 'Processos Jurídicos',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
