# Generated by Django 5.0.2 on 2025-09-02 19:18

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0010_auto_20250902_1609"),
    ]

    operations = [
        # Modificar modelo DocumentoJuridico existente
        migrations.AddField(
            model_name='documentojuridico',
            name='processo',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='assejus.processojuridico', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='documentojuridico',
            name='tipo_documento',
            field=models.CharField(choices=[('peticao', 'Petição'), ('sentenca', 'Sentença'), ('despacho', 'Despacho'), ('certidao', 'Certidão'), ('contrato', 'Contrato'), ('comprovante', 'Comprovante'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='documentojuridico',
            name='atendimento',
        ),
        migrations.RemoveField(
            model_name='documentojuridico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='documentojuridico',
            name='ativo',
        ),
        
        # Adicionar apenas os campos que não existem no modelo Andamento
        migrations.AddField(
            model_name='andamento',
            name='processo',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='assejus.processojuridico'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='descricao_detalhada',
            field=models.TextField(default='', help_text='Descrição completa do que aconteceu (ex.: audiência realizada, prazo protocolado, sentença publicada)', verbose_name='Descrição Detalhada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='andamento',
            name='observacoes_cliente',
            field=models.TextField(blank=True, help_text='Explicação simplificada do ocorrido em linguagem acessível', null=True, verbose_name='Observações para o Cliente'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='cliente_visualizou',
            field=models.BooleanField(default=False, verbose_name='Cliente Visualizou'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='data_visualizacao_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Visualização pelo Cliente'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='andamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Adicionar relacionamento many-to-many para anexos
        migrations.AddField(
            model_name='andamento',
            name='anexos',
            field=models.ManyToManyField(blank=True, related_name='andamentos', to='assejus.documentojuridico', verbose_name='Anexos'),
        ),
    ]
