# Generated by Django 5.0.2 on 2025-09-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0011_auto_20250902_1618"),
    ]

    operations = [
        # Remover campos obsoletos do modelo Andamento que existem no banco mas não no modelo atual
        migrations.RemoveField(
            model_name='andamento',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='descricao',
        ),
        # Remover outros campos que foram mencionados nas migrações 0009 mas podem não estar no modelo atual
        migrations.RemoveField(
            model_name='andamento',
            name='acoes_necessarias',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='acoes_necessarias_decisao',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='assunto_contato',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='conteudo_principal',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='conteudo_relevante',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='data_audiencia',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='data_decisao',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='decisoes_tomadas',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='forma_contato',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='impacto_caso',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='juiz_audiencia',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='local_audiencia',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='proximas_audiencias',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='proximos_passos_contato',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='tipo_decisao',
        ),
        migrations.RemoveField(
            model_name='andamento',
            name='tipo_documento',
        ),
        # Remover o campo atendimento que foi substituído por processo
        migrations.RemoveField(
            model_name='andamento',
            name='atendimento',
        ),
    ]
