# Generated by Django 5.0.2 on 2025-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0012_remove_obsolete_andamento_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='processojuridico',
            name='advogado_parte_contraria',
            field=models.CharField(
                blank=True,
                help_text='Nome do advogado ou procurador que representa a parte contrária',
                max_length=200,
                null=True,
                verbose_name='Advogado/Procurador da Parte Contrária'
            ),
        ),
    ]
