# Generated by Django 5.0.2 on 2025-09-03 12:22

import assejus.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0014_add_advogado_parte_contraria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentojuridico",
            options={
                "ordering": ["-data_upload"],
                "verbose_name": "Documento Jurídico",
                "verbose_name_plural": "Documentos Jurídicos",
            },
        ),
        migrations.AlterField(
            model_name="andamento",
            name="data_andamento",
            field=models.DateTimeField(verbose_name="Data do Andamento"),
        ),
        migrations.AlterField(
            model_name="andamento",
            name="tipo_andamento",
            field=models.CharField(
                choices=[
                    ("audiencia", "Audiência"),
                    ("despacho", "Despacho"),
                    ("prazo", "Prazo"),
                    ("sentenca", "Sentença"),
                    ("recurso", "Recurso"),
                    ("contato", "Contato"),
                    ("documento", "Documento"),
                    ("outro", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de Andamento",
            ),
        ),
        migrations.AlterField(
            model_name="andamento",
            name="usuario_registro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="andamentos_registrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Registrou",
            ),
        ),
        migrations.AlterField(
            model_name="documentojuridico",
            name="arquivo",
            field=models.FileField(
                help_text="Formatos aceitos: PDF, DOC, DOCX, JPG, PNG (máx. 10MB)",
                upload_to="documentos_juridicos/%Y/%m/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="documentojuridico",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="documentojuridico",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name="Título do Documento"),
        ),
        migrations.AlterField(
            model_name="documentojuridico",
            name="usuario_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_upload",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Fez Upload",
            ),
        ),
        migrations.AlterField(
            model_name="processojuridico",
            name="numero_processo",
            field=models.CharField(
                help_text="Formato CNJ: NNNNNNN-DD.AAAA.J.TR.OOOO (ex: 0001234-56.2024.8.26.0001)",
                max_length=50,
                unique=True,
                validators=[assejus.models.validar_numero_processo_cnj],
                verbose_name="Número do Processo",
            ),
        ),
    ]
