# Generated by Django 5.0.2 on 2025-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0015_alter_documentojuridico_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processojuridico",
            name="tipo_processo",
            field=models.CharField(
                choices=[
                    ("judicial", "Processo Judicial"),
                    ("administrativo", "Processo Administrativo"),
                ],
                default="judicial",
                max_length=20,
                verbose_name="Tipo de Processo",
            ),
        ),
        migrations.AddField(
            model_name="processojuridico",
            name="tipo_processo_administrativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sindicancia", "Sindicância"),
                    ("inquerito_policial_militar", "Inquérito Policial Militar"),
                    (
                        "processo_administrativo_ordinario",
                        "Processo Administrativo Ordinário",
                    ),
                    (
                        "processo_administrativo_sumario",
                        "Processo Administrativo Sumário",
                    ),
                    ("inquerito_tecnico", "Inquérito Técnico"),
                    ("conselho_justificacao", "Conselho de Justificação"),
                    ("conselho_disciplina", "Conselho de Disciplina"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo de Processo Administrativo",
            ),
        ),
        migrations.AddField(
            model_name="processojuridico",
            name="unidade_militar_apuração",
            field=models.CharField(
                blank=True,
                help_text="Nome da unidade militar responsável pela apuração do processo administrativo",
                max_length=200,
                null=True,
                verbose_name="Unidade Militar que está Apurando",
            ),
        ),
        migrations.AlterField(
            model_name="processojuridico",
            name="tipo_acao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil", "Ação Civil"),
                    ("trabalhista", "Ação Trabalhista"),
                    ("previdenciaria", "Ação Previdenciária"),
                    ("criminal", "Ação Criminal"),
                    ("administrativa", "Ação Administrativa"),
                    ("familiar", "Ação de Família"),
                    ("sucessao", "Inventário e Sucessão"),
                    ("outro", "Outro"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Ação",
            ),
        ),
        migrations.AlterField(
            model_name="processojuridico",
            name="vara_tribunal",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Vara/Tribunal"
            ),
        ),
    ]
