# Generated by Django 5.0.2 on 2025-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0016_processojuridico_tipo_processo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processojuridico",
            old_name="unidade_militar_apuração",
            new_name="unidade_militar_apuracao",
        ),
    ]
