# Generated by Django 5.0.2 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assejus",
            "0017_rename_unidade_militar_apuração_processojuridico_unidade_militar_apuracao",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="processojuridico",
            name="numero_processo",
            field=models.CharField(
                help_text="Para processos judiciais: formato CNJ (0001234-56.2024.8.26.0001). Para administrativos: qualquer formato.",
                max_length=50,
                unique=True,
                verbose_name="Número do Processo",
            ),
        ),
    ]
