# Generated by Django 5.0.2 on 2025-09-04 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0018_alter_processojuridico_numero_processo"),
        ("associados", "0013_associado_nome_mae_associado_nome_pai_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcuracaoAdJudicia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_poderes",
                    models.CharField(
                        choices=[
                            ("gerais", "Poderes Gerais"),
                            ("especificos", "Poderes Específicos"),
                            ("ambos", "Poderes Gerais e Específicos"),
                        ],
                        default="gerais",
                        max_length=20,
                        verbose_name="Tipo de Poderes",
                    ),
                ),
                (
                    "cargo_militar",
                    models.CharField(
                        help_text="Ex: 1º Sargento Policial Militar",
                        max_length=100,
                        verbose_name="Cargo Militar",
                    ),
                ),
                (
                    "matricula_funcional",
                    models.CharField(
                        help_text="Ex: 079966-1",
                        max_length=50,
                        verbose_name="Matrícula Funcional",
                    ),
                ),
                (
                    "rgpmpi",
                    models.CharField(
                        help_text="Ex: 1010528-92", max_length=50, verbose_name="RGPMPI"
                    ),
                ),
                (
                    "endereco_completo",
                    models.TextField(
                        help_text="Endereço completo do outorgante",
                        verbose_name="Endereço Completo",
                    ),
                ),
                (
                    "telefone_contato",
                    models.CharField(
                        help_text="Ex: 86 99472-1952",
                        max_length=20,
                        verbose_name="Telefone de Contato",
                    ),
                ),
                (
                    "email_contato",
                    models.EmailField(
                        help_text="E-mail do outorgante",
                        max_length=254,
                        verbose_name="E-mail de Contato",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Adicionais"
                    ),
                ),
                (
                    "texto_personalizado",
                    models.TextField(
                        blank=True,
                        help_text="Deixe em branco para usar o texto padrão. Use as variáveis: {outorgante_nome}, {outorgante_cpf}, {outorgante_cargo}, {outorgante_matricula}, {outorgante_rgpmpi}, {outorgante_endereco}, {outorgante_telefone}, {outorgante_email}, {outorgados_nomes}, {outorgados_oab}, {processo_numero}, {processo_vara}, {data_atual}",
                        null=True,
                        verbose_name="Texto Personalizado da Procuração",
                    ),
                ),
                (
                    "outorgados",
                    models.ManyToManyField(
                        related_name="procuracaoes_outorgado",
                        to="assejus.advogado",
                        verbose_name="Outorgado(s) (Advogado(s))",
                    ),
                ),
                (
                    "outorgante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procuracaoes_outorgante",
                        to="associados.associado",
                        verbose_name="Outorgante (Associado)",
                    ),
                ),
                (
                    "processo_especifico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Processo para o qual os poderes específicos são conferidos",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procuracaoes_especificas",
                        to="assejus.processojuridico",
                        verbose_name="Processo Específico",
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procuracaoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Criou",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procuração Ad Judicia",
                "verbose_name_plural": "Procurações Ad Judicia",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
