# Generated by Django 5.0.2 on 2025-09-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0019_procuracaoadjudicia"),
    ]

    operations = [
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="numero_processo_especifico",
            field=models.CharField(
                blank=True,
                help_text="Número do processo para poderes específicos (pode ser digitado livremente)",
                max_length=100,
                null=True,
                verbose_name="Número do Processo Específico",
            ),
        ),
        migrations.AlterField(
            model_name="procuracaoadjudicia",
            name="processo_especifico",
            field=models.ForeignKey(
                blank=True,
                help_text="Processo cadastrado no sistema (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procuracaoes_especificas",
                to="assejus.processojuridico",
                verbose_name="Processo Específico (Cadastrado)",
            ),
        ),
    ]
