# Generated by Django 5.0.2 on 2025-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0020_procuracaoadjudicia_numero_processo_especifico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="foto_outorgante",
            field=models.ImageField(
                blank=True,
                help_text="Foto do outorgante para incluir na procuração",
                null=True,
                upload_to="procuracaoes/fotos/",
                verbose_name="Foto do Outorgante",
            ),
        ),
    ]
