# Generated by Django 5.0.2 on 2025-09-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0021_add_foto_outorgante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procuracaoadjudicia",
            name="foto_outorgante",
        ),
    ]
