# Generated by Django 5.0.2 on 2025-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0022_remove_foto_outorgante"),
    ]

    operations = [
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="objetivos_especificos",
            field=models.TextField(
                blank=True,
                help_text="Descreva os objetivos específicos da procuração",
                null=True,
                verbose_name="Objetivos Específicos",
            ),
        ),
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="objetivos_gerais",
            field=models.TextField(
                blank=True,
                help_text="Descreva os objetivos gerais da procuração",
                null=True,
                verbose_name="Objetivos Gerais",
            ),
        ),
    ]
