# Generated by Django 5.0.2 on 2025-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0023_procuracaoadjudicia_objetivos_especificos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procuracaoadjudicia",
            name="objetivos_especificos",
        ),
        migrations.RemoveField(
            model_name="procuracaoadjudicia",
            name="objetivos_gerais",
        ),
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="poderes_especificos",
            field=models.TextField(
                blank=True,
                help_text="Descreva os poderes específicos da procuração",
                null=True,
                verbose_name="Poderes Específicos",
            ),
        ),
        migrations.AddField(
            model_name="procuracaoadjudicia",
            name="poderes_gerais",
            field=models.TextField(
                blank=True,
                help_text="Descreva os poderes gerais da procuração",
                null=True,
                verbose_name="Poderes Gerais",
            ),
        ),
    ]
