# Generated by Django 5.0.2 on 2025-09-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assejus", "0024_rename_objetivos_to_poderes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloPoderes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("civil", "Civil"),
                            ("criminal", "Criminal"),
                            ("trabalhista", "Trabalhista"),
                            ("administrativo", "Administrativo"),
                        ],
                        default="geral",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gerais", "Poderes Gerais"),
                            ("especificos", "Poderes Específicos"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Poderes",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo do Modelo")),
                (
                    "publico",
                    models.BooleanField(default=False, verbose_name="Modelo Público"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_poderes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Poderes",
                "verbose_name_plural": "Modelos de Poderes",
                "ordering": ["-data_criacao"],
                "unique_together": {("nome", "criado_por", "tipo")},
            },
        ),
    ]
