# Generated by Django 5.0.2 on 2025-08-13 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Associado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato XXX.XXX.XXX-XX",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="associados/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone"
                    ),
                ),
                ("celular", models.CharField(max_length=15, verbose_name="Celular")),
                (
                    "cep",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato XXXXX-XXX",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                        verbose_name="CEP",
                    ),
                ),
                ("rua", models.CharField(max_length=200, verbose_name="Rua")),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "matricula_militar",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Número da Matrícula Militar",
                    ),
                ),
                (
                    "posto_graduacao",
                    models.CharField(max_length=50, verbose_name="Posto/Graduação"),
                ),
                (
                    "unidade_lotacao",
                    models.CharField(max_length=100, verbose_name="Unidade de Lotação"),
                ),
                ("data_ingresso", models.DateField(verbose_name="Data de Ingresso")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("reserva", "Reserva"),
                            ("reformado", "Reformado"),
                            ("pensionista", "Pensionista"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Associado Ativo"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário do Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associado",
                "verbose_name_plural": "Associados",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Dependente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("filho", "Filho(a)"),
                            ("conjuge", "Cônjuge"),
                            ("pai", "Pai"),
                            ("mae", "Mãe"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato XXX.XXX.XXX-XX",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Dependente Ativo"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependentes",
                        to="associados.associado",
                        verbose_name="Associado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependente",
                "verbose_name_plural": "Dependentes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rg", "RG"),
                            ("cpf", "CPF"),
                            ("comprovante_residencia", "Comprovante de Residência"),
                            ("certidao_nascimento", "Certidão de Nascimento"),
                            ("certidao_casamento", "Certidão de Casamento"),
                            ("certidao_divorcio", "Certidão de Divórcio"),
                            ("declaracao_servico", "Declaração de Serviço"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="associados/documentos/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Documento Ativo"),
                ),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="associados.associado",
                        verbose_name="Associado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.AddIndex(
            model_name="associado",
            index=models.Index(fields=["cpf"], name="associados__cpf_f27c11_idx"),
        ),
        migrations.AddIndex(
            model_name="associado",
            index=models.Index(
                fields=["matricula_militar"], name="associados__matricu_730c33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="associado",
            index=models.Index(
                fields=["situacao"], name="associados__situaca_c73417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="associado",
            index=models.Index(fields=["ativo"], name="associados__ativo_f3bbed_idx"),
        ),
    ]
