# Generated by Django 5.0.2 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="associado",
            name="tipo_socio",
            field=models.CharField(
                choices=[
                    ("fundador", "Sócio Fundador"),
                    ("benemerito", "Sócio Benemérito"),
                    ("contribuinte", "Sócio Contribuinte"),
                ],
                default="contribuinte",
                max_length=20,
                verbose_name="Tipo de Sócio",
            ),
        ),
    ]
