# Generated by Django 5.0.2 on 2025-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0002_associado_tipo_socio"),
    ]

    operations = [
        migrations.AddField(
            model_name="associado",
            name="tipo_profissional",
            field=models.CharField(
                choices=[
                    ("bombeiro_militar", "Bombeiro Militar"),
                    ("policial_militar", "Policial Militar"),
                    ("civil", "Civil"),
                ],
                default="bombeiro_militar",
                max_length=20,
                verbose_name="Tipo de Profissional",
            ),
        ),
    ]
