# Generated by Django 5.0.2 on 2025-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0004_associado_nome_civil_alter_associado_posto_graduacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associado",
            name="posto_graduacao",
            field=models.CharField(
                choices=[
                    ("soldado_bm", "Soldado BM"),
                    ("cabo_bm", "Cabo BM"),
                    ("3sgt_bm", "3º Sargento BM"),
                    ("2sgt_bm", "2º Sargento BM"),
                    ("1sgt_bm", "1º Sargento BM"),
                    ("subten_bm", "Subtenente BM"),
                    ("asp_bm", "Aspirante BM"),
                    ("2ten_bm", "2º Tenente BM"),
                    ("1ten_bm", "1º Tenente BM"),
                    ("cap_bm", "Capitão BM"),
                    ("maj_bm", "Major BM"),
                    ("ten_cel_bm", "Tenente Coronel BM"),
                    ("cel_bm", "Coronel BM"),
                    ("soldado_pm", "Soldado PM"),
                    ("cabo_pm", "Cabo PM"),
                    ("3sgt_pm", "3º Sargento PM"),
                    ("2sgt_pm", "2º Sargento PM"),
                    ("1sgt_pm", "1º Sargento PM"),
                    ("subten_pm", "Subtenente PM"),
                    ("asp_pm", "Aspirante PM"),
                    ("2ten_pm", "2º Tenente PM"),
                    ("1ten_pm", "1º Tenente PM"),
                    ("cap_pm", "Capitão PM"),
                    ("maj_pm", "Major PM"),
                    ("ten_cel_pm", "Tenente Coronel PM"),
                    ("cel_pm", "Coronel PM"),
                    ("civil", "Civil"),
                    ("estudante", "Estudante"),
                    ("profissional_livre", "Profissional Liberal"),
                    ("servidor_publico", "Servidor Público"),
                    ("empresario", "Empresário"),
                    ("aposentado", "Aposentado"),
                ],
                default="civil",
                max_length=30,
                verbose_name="Posto/Graduação",
            ),
        ),
    ]
