# Generated by Django 5.0.2 on 2025-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0006_precadastroassociado"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependente",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="associados/dependentes/fotos/",
                verbose_name="Foto",
            ),
        ),
    ]
