# Generated by Django 5.0.2 on 2025-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0007_add_foto_dependente"),
    ]

    operations = [
        migrations.AddField(
            model_name="associado",
            name="nacionalidade",
            field=models.CharField(
                default="Brasileira", max_length=50, verbose_name="Nacionalidade"
            ),
        ),
        migrations.AddField(
            model_name="associado",
            name="naturalidade",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Naturalidade (Cidade/Estado)"
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="nacionalidade",
            field=models.CharField(
                default="Brasileira", max_length=50, verbose_name="Nacionalidade"
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="naturalidade",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Naturalidade (Cidade/Estado)"
            ),
        ),
    ]
