# Generated by Django 5.0.2 on 2025-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0008_add_naturalidade_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="associado",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="precadastroassociado",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
    ]
