# Generated by Django 5.0.2 on 2025-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0010_documento_dependente_alter_documento_associado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="tipo_personalizado",
            field=models.CharField(
                blank=True,
                help_text='Especifique o tipo de documento quando selecionar "Outro"',
                max_length=100,
                verbose_name="Tipo Personalizado",
            ),
        ),
    ]
