# Generated by Django 5.0.2 on 2025-09-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0011_documento_tipo_personalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="precadastroassociado",
            name="comprovante_residencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pre_cadastros/documentos/residencia/",
                verbose_name="Comprovante de Residência",
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="copia_cpf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pre_cadastros/documentos/cpf/",
                verbose_name="Cópia do CPF",
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="copia_rg",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pre_cadastros/documentos/rg/",
                verbose_name="Cópia do RG",
            ),
        ),
    ]
