# Generated by Django 5.0.2 on 2025-09-03 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0012_precadastroassociado_comprovante_residencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="associado",
            name="nome_mae",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AddField(
            model_name="associado",
            name="nome_pai",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AddField(
            model_name="associado",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("rgpm", "RGPM"),
                    ("rgbm", "RGBM"),
                    ("gip", "GIP"),
                    ("rg", "RG"),
                ],
                default="rg",
                max_length=10,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="nome_mae",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="nome_pai",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("reserva", "Reserva"),
                    ("reformado", "Reformado"),
                    ("pensionista", "Pensionista"),
                ],
                default="ativo",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AddField(
            model_name="precadastroassociado",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("rgpm", "RGPM"),
                    ("rgbm", "RGBM"),
                    ("gip", "GIP"),
                    ("rg", "RG"),
                ],
                default="rg",
                max_length=10,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.CreateModel(
            name="DependentePreCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("filho", "Filho(a)"),
                            ("conjuge", "Cônjuge"),
                            ("pai", "Pai"),
                            ("mae", "Mãe"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="associados/pre_cadastro/dependentes/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato XXX.XXX.XXX-XX",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "pre_cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependentes",
                        to="associados.precadastroassociado",
                        verbose_name="Pré-Cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependente do Pré-Cadastro",
                "verbose_name_plural": "Dependentes do Pré-Cadastro",
                "ordering": ["nome"],
            },
        ),
    ]
