# Generated by Django 4.2.7 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('duplo', 'Duplo'), ('triplo', 'Triplo'), ('suite', 'Suíte')], max_length=20, verbose_name='Tipo de Quarto')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Diária')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção'), ('reservado', 'Reservado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('ar_condicionado', models.BooleanField(default=True, verbose_name='Ar Condicionado')),
                ('tv', models.BooleanField(default=True, verbose_name='TV')),
                ('wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('banheiro_privativo', models.BooleanField(default=True, verbose_name='Banheiro Privativo')),
                ('frigobar', models.BooleanField(default=False, verbose_name='Frigobar')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hospede', models.CharField(choices=[('associado', 'Associado'), ('nao_associado', 'Não Associado')], max_length=20, verbose_name='Tipo de Hóspede')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('passaporte', 'Passaporte'), ('cnh', 'CNH'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número do Documento')),
                ('orgao_emissor', models.CharField(blank=True, max_length=10, verbose_name='Órgão Emissor')),
                ('uf_emissor', models.CharField(blank=True, max_length=2, verbose_name='UF Emissor')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, verbose_name='Telefone Secundário')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospedagens', to='associados.associado', verbose_name='Associado')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=20, unique=True, verbose_name='Código da Reserva')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(verbose_name='Data de Saída')),
                ('hora_entrada', models.TimeField(default='14:00:00', verbose_name='Hora de Entrada')),
                ('hora_saida', models.TimeField(default='12:00:00', verbose_name='Hora de Saída')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Diária')),
                ('quantidade_diarias', models.PositiveIntegerField(verbose_name='Quantidade de Diárias')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.hospede', verbose_name='Hóspede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_real', models.DateTimeField(verbose_name='Data e Hora de Entrada Real')),
                ('data_saida_real', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Saída Real')),
                ('valor_diaria_real', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Diária Real')),
                ('quantidade_diarias_real', models.PositiveIntegerField(verbose_name='Quantidade de Diárias Real')),
                ('valor_total_real', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Real')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.hospede', verbose_name='Hóspede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.quarto', verbose_name='Quarto')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Hospedagem',
                'verbose_name_plural': 'Hospedagens',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ServicoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('tipo', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lavanderia', 'Lavanderia'), ('limpeza', 'Limpeza'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço Adicional',
                'verbose_name_plural': 'Serviços Adicionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('data_utilizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Utilização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.hospedagem', verbose_name='Hospedagem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_transito.servicoadicional', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço Utilizado',
                'verbose_name_plural': 'Serviços Utilizados',
                'ordering': ['-data_utilizacao'],
            },
        ),
    ]
