# Generated by Django 5.0.2 on 2025-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_transito", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="hora_entrada",
            field=models.TimeField(default="14:00", verbose_name="Hora de Entrada"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="hora_saida",
            field=models.TimeField(default="12:00", verbose_name="Hora de Saída"),
        ),
    ]
