# Generated by Django 5.0.2 on 2025-08-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_transito", "0002_alter_reserva_hora_entrada_alter_reserva_hora_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospedagem",
            name="quantidade_diarias_real",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Quantidade de Diárias Real"
            ),
        ),
        migrations.AlterField(
            model_name="hospedagem",
            name="valor_total_real",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Total Real",
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="tipo_hospede",
            field=models.CharField(
                choices=[
                    ("associado", "Associado"),
                    ("visitante", "Visitante"),
                    ("funcionario", "Funcionário"),
                    ("conveniado", "Conveniado"),
                ],
                max_length=20,
                verbose_name="Tipo de Hóspede",
            ),
        ),
    ]
