# Generated by Django 5.0.2 on 2025-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_transito", "0003_alter_hospedagem_quantidade_diarias_real_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospede",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="hospedes/", verbose_name="Foto"
            ),
        ),
    ]
