# Generated by Django 5.0.2 on 2025-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitucionalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_principal",
                    models.CharField(default="ABMEPI", max_length=200),
                ),
                (
                    "subtitulo_hero",
                    models.TextField(
                        default="Associação de Bombeiros e Policiais Militares - Unindo forças para proteger e servir nossa comunidade"
                    ),
                ),
                (
                    "titulo_sobre",
                    models.CharField(default="Sobre a ABMEPI", max_length=200),
                ),
                (
                    "texto_sobre_1",
                    models.TextField(
                        default="A Associação de Bombeiros e Policiais Militares (ABMEPI) é uma entidade dedicada ao bem-estar e desenvolvimento profissional dos membros das forças de segurança pública."
                    ),
                ),
                (
                    "texto_sobre_2",
                    models.TextField(
                        default="Nossa missão é proporcionar suporte integral aos associados, oferecendo serviços de qualidade, assessoria jurídica especializada e uma rede de benefícios que valoriza o trabalho e dedicação desses profissionais."
                    ),
                ),
                (
                    "texto_sobre_3",
                    models.TextField(
                        default="Com anos de experiência e uma equipe comprometida, a ABMEPI se tornou referência em gestão associativa, sempre priorizando a excelência e a satisfação de nossos membros."
                    ),
                ),
                (
                    "titulo_cta",
                    models.CharField(
                        default="Pronto para se juntar a nós?", max_length=200
                    ),
                ),
                (
                    "texto_cta",
                    models.TextField(
                        default="Acesse nosso sistema completo e descubra todos os benefícios disponíveis para nossos associados. Faça login agora e aproveite!"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(default="(11) 99999-9999", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(default="contato@abmepi.org.br", max_length=254),
                ),
                ("endereco", models.CharField(default="São Paulo, SP", max_length=200)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("mostrar_estatisticas", models.BooleanField(default=True)),
                ("mostrar_servicos", models.BooleanField(default=True)),
                ("mostrar_sobre", models.BooleanField(default=True)),
                ("mostrar_cta", models.BooleanField(default=True)),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="Descrição para SEO"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Palavras-chave para SEO", max_length=500
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração Institucional",
                "verbose_name_plural": "Configurações Institucionais",
            },
        ),
    ]
