# Generated by Django 5.0.2 on 2025-08-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_institucionalconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Post"),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo do Post")),
                (
                    "tipo_post",
                    models.CharField(
                        choices=[
                            ("noticia", "Notícia"),
                            ("evento", "Evento"),
                            ("treinamento", "Treinamento"),
                            ("premiacao", "Premiação"),
                            ("convenio", "Convênio"),
                            ("outro", "Outro"),
                        ],
                        default="noticia",
                        max_length=20,
                        verbose_name="Tipo de Post",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="feed_posts/",
                        verbose_name="Imagem do Post",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        default="ABMEPI Oficial",
                        max_length=100,
                        verbose_name="Autor do Post",
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Likes"
                    ),
                ),
                (
                    "comentarios",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Comentários"
                    ),
                ),
                (
                    "compartilhamentos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Compartilhamentos"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Post Ativo")),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Post em Destaque"),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post do Feed",
                "verbose_name_plural": "Posts do Feed",
                "ordering": ["-destaque", "-ordem_exibicao", "-data_publicacao"],
            },
        ),
    ]
