# Generated by Django 5.0.2 on 2025-08-19 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_comentario_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="nome_anonimo",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nome do Usuário Anônimo",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
