# Generated by Django 5.0.2 on 2025-08-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_comentario_nome_anonimo_alter_comentario_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssejurInformativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título do Informativo"
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo do Informativo")),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("fas fa-exclamation-triangle", "⚠️ Triângulo (Alerta)"),
                            ("fas fa-clock", "🕐 Relógio (Horário)"),
                            ("fas fa-phone", "📞 Telefone (Contato)"),
                            ("fas fa-envelope", "✉️ Envelope (Email)"),
                            ("fas fa-map-marker-alt", "📍 Marcador (Localização)"),
                            ("fas fa-calendar", "📅 Calendário (Data)"),
                            ("fas fa-info-circle", "ℹ️ Informação"),
                            ("fas fa-bullhorn", "📢 Megafone (Anúncio)"),
                        ],
                        default="fas fa-info-circle",
                        max_length=30,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "cor_icone",
                    models.CharField(
                        default="#3498db",
                        max_length=7,
                        verbose_name="Cor do Ícone (HEX)",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Informativo Ativo"),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informativo ASSEJUR",
                "verbose_name_plural": "Informativos ASSEJUR",
                "ordering": ["-ordem_exibicao", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="AssejurNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Notícia"),
                ),
                (
                    "resumo",
                    models.TextField(max_length=500, verbose_name="Resumo da Notícia"),
                ),
                (
                    "conteudo",
                    models.TextField(blank=True, verbose_name="Conteúdo Completo"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("direito_previdenciario", "Direito Previdenciário"),
                            ("direito_administrativo", "Direito Administrativo"),
                            ("direito_militar", "Direito Militar"),
                            ("direito_civil", "Direito Civil"),
                            ("direito_penal", "Direito Penal"),
                            ("direito_trabalhista", "Direito Trabalhista"),
                            ("direito_constitucional", "Direito Constitucional"),
                            ("direito_tributario", "Direito Tributário"),
                        ],
                        default="direito_previdenciario",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("fas fa-gavel", "🔨 Gavel (Direito)"),
                            ("fas fa-balance-scale", "⚖️ Balança (Justiça)"),
                            ("fas fa-shield-alt", "🛡️ Escudo (Militar)"),
                            ("fas fa-user-tie", "👔 Usuário (Civil)"),
                            ("fas fa-briefcase", "💼 Pasta (Trabalhista)"),
                            ("fas fa-book", "📚 Livro (Constitucional)"),
                            ("fas fa-calculator", "🧮 Calculadora (Tributário)"),
                            ("fas fa-university", "🏛️ Universidade (Institucional)"),
                        ],
                        default="fas fa-gavel",
                        max_length=30,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "link_externo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link Externo (Ler mais)"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Tags (separadas por vírgula)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Notícia Ativa"),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, verbose_name="Destacar no Carrossel"
                    ),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "visualizacoes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Visualizações"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia ASSEJUR",
                "verbose_name_plural": "Notícias ASSEJUR",
                "ordering": ["-destaque", "-ordem_exibicao", "-data_publicacao"],
            },
        ),
    ]
