# Generated by Django 5.0.2 on 2025-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_assejurinformativo_assejurnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="assejurnews",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="assejur_news/",
                verbose_name="Imagem da Notícia",
            ),
        ),
        migrations.AddField(
            model_name="assejurnews",
            name="imagem_legenda",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Legenda da Imagem"
            ),
        ),
    ]
