# Generated by Django 5.0.2 on 2025-08-22 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_assejurnews_imagem_assejurnews_imagem_legenda"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssejurNewsComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_anonimo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Usuário Anônimo",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Comentário")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Comentário Ativo"),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="core.assejurnews",
                        verbose_name="Notícia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário de Notícia ASSEJUR",
                "verbose_name_plural": "Comentários de Notícias ASSEJUR",
                "ordering": ["data_criacao"],
            },
        ),
    ]
