# Generated by Django 5.0.2 on 2025-08-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assejurnewscomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Chave da Sessão')),
                ('nome_anonimo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Usuário Anônimo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Like Anônimo',
                'verbose_name_plural': 'Likes Anônimos',
                'ordering': ['-data_criacao'],
                'unique_together': {('post', 'session_key')},
            },
        ),
    ]
