# Generated by Django 5.0.2 on 2025-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_likeanonimo"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucionalconfig",
            name="assejur_facebook_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Facebook ASSEJUR"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="assejur_instagram_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Instagram ASSEJUR"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="assejur_linkedin_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="LinkedIn ASSEJUR"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="assejur_twitter_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Twitter ASSEJUR"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="assejur_youtube_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="YouTube ASSEJUR"
            ),
        ),
    ]
