# Generated by Django 5.0.2 on 2025-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_assejur_social_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_culturais",
            field=models.BooleanField(default=True, verbose_name="Serviços Culturais"),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_educacionais",
            field=models.BooleanField(
                default=True, verbose_name="Serviços Educacionais"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_esportivos",
            field=models.BooleanField(default=True, verbose_name="Serviços Esportivos"),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_financeiros",
            field=models.BooleanField(
                default=True, verbose_name="Serviços Financeiros"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_juridicos",
            field=models.BooleanField(default=True, verbose_name="Serviços Jurídicos"),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_medicos",
            field=models.BooleanField(default=True, verbose_name="Serviços Médicos"),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_odontologicos",
            field=models.BooleanField(
                default=True, verbose_name="Serviços Odontológicos"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_psicologicos",
            field=models.BooleanField(
                default=True, verbose_name="Serviços Psicológicos"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_recreativos",
            field=models.BooleanField(
                default=True, verbose_name="Serviços Recreativos"
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_sociais",
            field=models.BooleanField(default=True, verbose_name="Serviços Sociais"),
        ),
    ]
