# Generated by Django 5.0.2 on 2025-08-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_institucionalconfig_servicos_culturais_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_culturais",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_educacionais",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_esportivos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_financeiros",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_juridicos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_medicos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_odontologicos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_psicologicos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_recreativos",
        ),
        migrations.RemoveField(
            model_name="institucionalconfig",
            name="servicos_sociais",
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="servicos_personalizados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de serviços em formato JSON: [{'nome': 'Nome do Serviço', 'ativo': true, 'icone': 'fa-icon'}]",
                verbose_name="Serviços Personalizados",
            ),
        ),
    ]
