# Generated by Django 5.0.2 on 2025-08-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_institucionalconfig_servicos_personalizados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucionalconfig",
            name="hotel_transito_imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hotel_transito/",
                verbose_name="Imagem do Hotel de Trânsito",
            ),
        ),
        migrations.AddField(
            model_name="institucionalconfig",
            name="hotel_transito_telefone",
            field=models.CharField(
                default="(11) 99999-9999",
                max_length=20,
                verbose_name="Telefone do Hotel de Trânsito",
            ),
        ),
    ]
