# Generated by Django 5.0.2 on 2025-08-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_institucionalconfig_hotel_transito_imagem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("administrador_sistema", "Administrador do Sistema"),
                    ("associado", "Associado"),
                    ("advogado", "Advogado"),
                    ("psicologo", "Psicólogo"),
                    ("atendente_advogado", "Atendente de Advogado"),
                    ("atendente_psicologo", "Atendente de Psicólogo"),
                    ("atendente_geral", "Atendente Geral"),
                ],
                default="associado",
                max_length=25,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
