# Generated by Django 5.0.2 on 2025-08-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_update_tipo_usuario_choices"),
        ("core", "0015_update_tipo_usuario_choices"),
    ]

    operations = []
