# Generated by Django 5.0.2 on 2025-09-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_configuracaocobranca_usuario_primeiro_acesso"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="senha_temporaria",
            field=models.CharField(
                blank=True,
                help_text="Senha em texto plano para visualização de administradores (apenas temporariamente)",
                max_length=128,
                null=True,
                verbose_name="Senha Temporária",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="senha_temporaria_expira",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que a senha temporária expira",
                null=True,
                verbose_name="Expiração da Senha Temporária",
            ),
        ),
    ]
