# Generated by Django 5.0.2 on 2025-09-02 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_usuario_senha_temporaria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva_hotel", "Reserva de Hotel"),
                            ("mensalidade_vencida", "Mensalidade Vencida"),
                            ("atendimento_juridico", "Atendimento Jurídico"),
                            ("atendimento_psicologico", "Atendimento Psicológico"),
                            ("sistema", "Sistema"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("lida", "Lida"),
                            ("resolvida", "Resolvida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo do Objeto"
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID do Objeto"
                    ),
                ),
                ("url_acao", models.URLField(blank=True, verbose_name="URL de Ação")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_leitura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Leitura"
                    ),
                ),
                (
                    "data_resolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Resolução"
                    ),
                ),
                (
                    "prioridade",
                    models.PositiveIntegerField(default=1, verbose_name="Prioridade"),
                ),
                (
                    "usuario_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Destino",
                    ),
                ),
                (
                    "usuario_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificacoes_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-prioridade", "-data_criacao"],
            },
        ),
    ]
