# Generated by Django 5.0.2 on 2025-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_notificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExPresidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "posto_graduacao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Posto/Graduação"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ex_presidentes/",
                        verbose_name="Foto",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Início do Mandato")),
                ("periodo_fim", models.DateField(verbose_name="Fim do Mandato")),
                ("biografia", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "principais_realizacoes",
                    models.TextField(blank=True, verbose_name="Principais Realizações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ex-Presidente",
                "verbose_name_plural": "Ex-Presidentes",
                "ordering": ["ordem_exibicao", "periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaAssociacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_marcante", models.DateField(verbose_name="Data Marcante")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fundacao", "Fundação"),
                            ("conquista", "Conquista"),
                            ("evento", "Evento Importante"),
                            ("reconhecimento", "Reconhecimento"),
                            ("expansao", "Expansão"),
                            ("outro", "Outro"),
                        ],
                        default="evento",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="historia/",
                        verbose_name="Imagem",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marco Histórico",
                "verbose_name_plural": "História da Associação",
                "ordering": ["ordem_exibicao", "data_marcante"],
            },
        ),
    ]
