# Generated by Django 5.0.2 on 2025-09-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_expresidente_historiaassociacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiaassociacao",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="historia/",
                verbose_name="Imagem Principal",
            ),
        ),
        migrations.CreateModel(
            name="HistoriaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="historia/galeria/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda da Imagem"
                    ),
                ),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria_imagens",
                        to="core.historiaassociacao",
                        verbose_name="Evento Histórico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da História",
                "verbose_name_plural": "Imagens da História",
                "ordering": ["evento", "ordem_exibicao", "created_at"],
            },
        ),
    ]
