# Generated by Django 5.0.2 on 2025-09-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_historiaassociacao_imagem_historiaimagem"),
    ]

    operations = [
        migrations.AddField(
            model_name='assejurnews',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_juridicas/', verbose_name='Imagem da Notícia'),
        ),
    ]
