# Generated by Django 5.0.2 on 2025-08-23 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associados", "0006_precadastroassociado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_primeira_consulta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Primeira Consulta"
                    ),
                ),
                (
                    "observacoes_iniciais",
                    models.TextField(blank=True, verbose_name="Observações Iniciais"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "associado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="associados.associado",
                        verbose_name="Associado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["associado__nome"],
            },
        ),
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "historico_familiar",
                    models.TextField(blank=True, verbose_name="Histórico Familiar"),
                ),
                (
                    "historico_pessoal",
                    models.TextField(blank=True, verbose_name="Histórico Pessoal"),
                ),
                ("queixa_principal", models.TextField(verbose_name="Queixa Principal")),
                (
                    "hipotese_diagnostica",
                    models.TextField(blank=True, verbose_name="Hipótese Diagnóstica"),
                ),
                (
                    "plano_terapeutico",
                    models.TextField(blank=True, verbose_name="Plano Terapêutico"),
                ),
                (
                    "observacoes_gerais",
                    models.TextField(blank=True, verbose_name="Observações Gerais"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prontuário",
                "verbose_name_plural": "Prontuários",
            },
        ),
        migrations.CreateModel(
            name="Psicologo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "crp",
                    models.CharField(max_length=20, unique=True, verbose_name="CRP"),
                ),
                (
                    "especialidades",
                    models.TextField(blank=True, verbose_name="Especialidades"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psicólogo",
                "verbose_name_plural": "Psicólogos",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="psicologo_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="psicologia.psicologo",
                verbose_name="Psicólogo Responsável",
            ),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("laudo", "Laudo"),
                            ("relatorio", "Relatório"),
                            ("atestado", "Atestado"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos_psicologia/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.psicologo",
                        verbose_name="Psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Sessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="Data e Hora")),
                (
                    "duracao",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Duração (minutos)",
                    ),
                ),
                (
                    "tipo_sessao",
                    models.CharField(
                        choices=[
                            ("avaliacao", "Avaliação"),
                            ("terapia", "Terapia"),
                            ("retorno", "Retorno"),
                            ("emergencial", "Emergencial"),
                        ],
                        default="terapia",
                        max_length=20,
                        verbose_name="Tipo de Sessão",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("remarcada", "Remarcada"),
                        ],
                        default="agendada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.psicologo",
                        verbose_name="Psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão",
                "verbose_name_plural": "Sessões",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="Evolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_evolucao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Evolução"
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo da Evolução")),
                (
                    "observacoes_terapeuta",
                    models.TextField(
                        blank=True, verbose_name="Observações do Terapeuta"
                    ),
                ),
                (
                    "proximos_passos",
                    models.TextField(blank=True, verbose_name="Próximos Passos"),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.sessao",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolução",
                "verbose_name_plural": "Evoluções",
                "ordering": ["-data_evolucao"],
            },
        ),
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de Fim")),
                (
                    "disponivel",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.psicologo",
                        verbose_name="Psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda",
                "verbose_name_plural": "Agendas",
                "ordering": ["data", "hora_inicio"],
                "unique_together": {("psicologo", "data", "hora_inicio")},
            },
        ),
    ]
