# Generated by Django 5.0.2 on 2025-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psicologo",
            name="aceita_planos_saude",
            field=models.BooleanField(
                default=False, verbose_name="Aceita Planos de Saúde"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="areas_atuacao",
            field=models.TextField(blank=True, verbose_name="Áreas de Atuação"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="curriculo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="psicologos/curriculos/",
                verbose_name="Currículo",
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="cursos_complementares",
            field=models.TextField(blank=True, verbose_name="Cursos Complementares"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="documentos_complementares",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="psicologos/documentos/",
                verbose_name="Documentos Complementares",
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="email_secundario",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail Secundário"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="endereco",
            field=models.CharField(blank=True, max_length=200, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="estado",
            field=models.CharField(blank=True, max_length=2, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="experiencia_profissional",
            field=models.TextField(blank=True, verbose_name="Experiência Profissional"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="formacao_academica",
            field=models.TextField(blank=True, verbose_name="Formação Acadêmica"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="psicologos/fotos/",
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="horario_atendimento",
            field=models.TextField(blank=True, verbose_name="Horário de Atendimento"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="numero",
            field=models.CharField(blank=True, max_length=10, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="orgao_emissor",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Órgão Emissor"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="planos_aceitos",
            field=models.TextField(blank=True, verbose_name="Planos Aceitos"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="rg",
            field=models.CharField(blank=True, max_length=20, verbose_name="RG"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="telefone_secundario",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefone Secundário"
            ),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="uf_crp",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF do CRP"),
        ),
        migrations.AddField(
            model_name="psicologo",
            name="valor_consulta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Valor da Consulta",
            ),
        ),
        migrations.AlterField(
            model_name="psicologo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="psicologo",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
    ]
