# Generated by Django 5.0.2 on 2025-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0002_add_missing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="prontuario",
            name="consideracoes_especiais",
            field=models.TextField(
                blank=True,
                help_text="Aspectos que merecem atenção especial",
                verbose_name="Considerações Especiais",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="expectativas_tratamento",
            field=models.TextField(
                blank=True,
                help_text="O que o paciente espera alcançar",
                verbose_name="Expectativas do Tratamento",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="fatores_estressores",
            field=models.TextField(
                blank=True,
                help_text="Principais fontes de estresse",
                verbose_name="Fatores Estressores",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="historico_medico",
            field=models.TextField(
                blank=True,
                help_text="Doenças, medicações, tratamentos médicos",
                verbose_name="Histórico Médico",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="historico_psicologico",
            field=models.TextField(
                blank=True,
                help_text="Tratamentos psicológicos anteriores, diagnósticos",
                verbose_name="Histórico Psicológico",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="objetivos_tratamento",
            field=models.TextField(
                blank=True,
                help_text="Objetivos específicos e mensuráveis",
                verbose_name="Objetivos do Tratamento",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="prazo_estimado",
            field=models.TextField(
                blank=True,
                help_text="Prazo estimado para o tratamento",
                verbose_name="Prazo Estimado",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="queixas_secundarias",
            field=models.TextField(
                blank=True,
                help_text="Outros sintomas ou problemas relatados",
                verbose_name="Queixas Secundárias",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="recomendacoes",
            field=models.TextField(
                blank=True,
                help_text="Recomendações para paciente e familiares",
                verbose_name="Recomendações",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="recursos_coping",
            field=models.TextField(
                blank=True,
                help_text="Estratégias para lidar com problemas",
                verbose_name="Recursos de Coping",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="sintomas_principais",
            field=models.TextField(
                blank=True,
                help_text="Sintomas mais relevantes para a avaliação",
                verbose_name="Sintomas Principais",
            ),
        ),
        migrations.AddField(
            model_name="prontuario",
            name="tecnicas_intervencao",
            field=models.TextField(
                blank=True,
                help_text="Técnicas específicas que serão utilizadas",
                verbose_name="Técnicas de Intervenção",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="hipotese_diagnostica",
            field=models.TextField(
                blank=True,
                help_text="Impressão clínica inicial",
                verbose_name="Hipótese Diagnóstica",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="historico_familiar",
            field=models.TextField(
                blank=True,
                help_text="Histórico familiar relevante para o caso",
                verbose_name="Histórico Familiar",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="historico_pessoal",
            field=models.TextField(
                blank=True,
                help_text="Experiências e vivências do paciente",
                verbose_name="Histórico Pessoal",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="observacoes_gerais",
            field=models.TextField(
                blank=True,
                help_text="Observações gerais sobre o caso",
                verbose_name="Observações Gerais",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="plano_terapeutico",
            field=models.TextField(
                blank=True,
                help_text="Estratégias e técnicas de intervenção",
                verbose_name="Plano Terapêutico",
            ),
        ),
        migrations.AlterField(
            model_name="prontuario",
            name="queixa_principal",
            field=models.TextField(
                help_text="Motivo principal que levou o paciente a buscar atendimento",
                verbose_name="Queixa Principal",
            ),
        ),
    ]
