# Generated by Django 5.0.2 on 2025-08-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0003_prontuario_consideracoes_especiais_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PsicologoResponsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "motivo_transferencia",
                    models.TextField(
                        blank=True, verbose_name="Motivo da Transferência"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.psicologo",
                        verbose_name="Psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psicólogo Responsável",
                "verbose_name_plural": "Psicólogos Responsáveis",
                "ordering": ["-data_inicio"],
                "unique_together": {("paciente", "psicologo", "data_inicio")},
            },
        ),
    ]
