# Generated by Django 5.0.2 on 2025-08-24 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0007_add_foto_dependente"),
        ("psicologia", "0004_psicologoresponsavel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="psicologoresponsavel",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name": "Psicólogo Responsável (Deprecated)",
                "verbose_name_plural": "Psicólogos Responsáveis (Deprecated)",
            },
        ),
        migrations.AlterField(
            model_name="paciente",
            name="associado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="associados.associado",
                verbose_name="Associado",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="psicologo_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes_responsavel",
                to="psicologia.psicologo",
                verbose_name="Psicólogo Responsável Principal",
            ),
        ),
        migrations.CreateModel(
            name="PacientePsicologo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(verbose_name="Data de Início do Atendimento"),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Fim do Atendimento"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Atendimento Ativo"),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Psicólogo Principal"
                    ),
                ),
                (
                    "especialidade_foco",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Especialidade/Foco do Atendimento",
                    ),
                ),
                (
                    "motivo_inicio",
                    models.TextField(
                        blank=True, verbose_name="Motivo do Início do Atendimento"
                    ),
                ),
                (
                    "motivo_encerramento",
                    models.TextField(blank=True, verbose_name="Motivo do Encerramento"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psicologia.psicologo",
                        verbose_name="Psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente-Psicólogo",
                "verbose_name_plural": "Relacionamentos Paciente-Psicólogo",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="psicologos",
            field=models.ManyToManyField(
                blank=True,
                through="psicologia.PacientePsicologo",
                to="psicologia.psicologo",
                verbose_name="Psicólogos",
            ),
        ),
        migrations.AddIndex(
            model_name="pacientepsicologo",
            index=models.Index(
                fields=["paciente", "ativo"], name="psicologia__pacient_0845b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pacientepsicologo",
            index=models.Index(
                fields=["psicologo", "ativo"], name="psicologia__psicolo_4f6f53_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pacientepsicologo",
            unique_together={("paciente", "psicologo")},
        ),
    ]
