# Generated by Django 5.0.2 on 2025-08-24 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0007_add_foto_dependente"),
        ("psicologia", "0006_alter_paciente_associado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="associado",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="associados.associado",
                verbose_name="Associado",
            ),
        ),
    ]
