# Generated by Django 5.0.2 on 2025-08-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0007_alter_paciente_associado"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pacientepsicologo",
            unique_together=set(),
        ),
    ]
