# Generated by Django 5.0.2 on 2025-09-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0008_alter_pacientepsicologo_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psicologo",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
