# Generated by Django 5.0.2 on 2025-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0009_alter_psicologo_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psicologo",
            name="orgao_emissor",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Órgão Emissor"
            ),
        ),
    ]
