# Generated by Django 5.0.2 on 2025-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicologia", "0010_fix_orgao_emissor_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psicologo",
            name="cpf",
            field=models.CharField(
                blank=True, 
                max_length=20, 
                null=True, 
                unique=True, 
                verbose_name="CPF"
            ),
        ),
    ]
