# Generated by Django 5.0.2 on 2025-08-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associados", "0005_alter_associado_posto_graduacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaBeneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Categoria"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ícone (FontAwesome)"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Categoria Ativa"),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Benefício",
                "verbose_name_plural": "Categorias de Benefícios",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaParceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "razao_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razão Social"
                    ),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "contato_principal",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contato Principal"
                    ),
                ),
                (
                    "telefone_contato",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone do Contato"
                    ),
                ),
                (
                    "email_contato",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail do Contato"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Empresa Ativa"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Empresa Parceira",
                "verbose_name_plural": "Empresas Parceiras",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Convênio"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("saude", "Saúde"),
                            ("educacao", "Educação"),
                            ("lazer", "Lazer"),
                            ("comercio", "Comércio"),
                            ("servicos", "Serviços"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("pendente", "Pendente"),
                            ("expirado", "Expirado"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "desconto",
                    models.CharField(max_length=100, verbose_name="Desconto Oferecido"),
                ),
                (
                    "condicoes",
                    models.TextField(blank=True, verbose_name="Condições do Convênio"),
                ),
                (
                    "documentos_necessarios",
                    models.TextField(blank=True, verbose_name="Documentos Necessários"),
                ),
                (
                    "arquivos_anexados",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="beneficios/convenios/",
                        verbose_name="Arquivos Anexados",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Convênio Ativo"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convenios",
                        to="beneficios.empresaparceira",
                        verbose_name="Empresa Parceira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convênio",
                "verbose_name_plural": "Convênios",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioBeneficios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("beneficios_por_categoria", "Benefícios por Categoria"),
                            ("beneficios_por_associado", "Benefícios por Associado"),
                            ("beneficios_por_empresa", "Benefícios por Empresa"),
                            ("utilizacao_mensal", "Utilização Mensal"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Período Início")),
                ("periodo_fim", models.DateField(verbose_name="Período Fim")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="beneficios/relatorios/",
                        verbose_name="Arquivo do Relatório",
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Geração"
                    ),
                ),
                (
                    "usuario_geracao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Gerou",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Benefícios",
                "verbose_name_plural": "Relatórios de Benefícios",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("utilizado", "Utilizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Aprovação"
                    ),
                ),
                (
                    "data_utilizacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Utilização"
                    ),
                ),
                (
                    "valor_beneficio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor do Benefício",
                    ),
                ),
                (
                    "desconto_aplicado",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Desconto Aplicado"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="beneficios/comprovantes/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="associados.associado",
                        verbose_name="Associado",
                    ),
                ),
                (
                    "usuario_aprovacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficios_aprovados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Aprovou",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="beneficios.convenio",
                        verbose_name="Convênio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício",
                "verbose_name_plural": "Benefícios",
                "ordering": ["-data_solicitacao"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="beneficios__status_0c11da_idx"
                    ),
                    models.Index(
                        fields=["associado", "status"],
                        name="beneficios__associa_ccd2e3_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="convenio",
            index=models.Index(fields=["status"], name="beneficios__status_d99058_idx"),
        ),
        migrations.AddIndex(
            model_name="convenio",
            index=models.Index(
                fields=["categoria"], name="beneficios__categor_46fb18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="convenio",
            index=models.Index(fields=["ativo"], name="beneficios__ativo_7b6df9_idx"),
        ),
    ]
