# Generated by Django 5.0.2 on 2025-09-04 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associados", "0013_associado_nome_mae_associado_nome_pai_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoDiretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Cargo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição do Cargo"),
                ),
                (
                    "ordem_hierarquica",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = mais alto, 100 = mais baixo",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Ordem Hierárquica",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Cargo Ativo"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo da Diretoria",
                "verbose_name_plural": "Cargos da Diretoria",
                "ordering": ["ordem_hierarquica", "nome"],
            },
        ),
        migrations.CreateModel(
            name="MembroDiretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Membro Ativo"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_diretoria",
                        to="associados.associado",
                        verbose_name="Associado",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="diretoria.cargodiretoria",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Diretoria",
                "verbose_name_plural": "Membros da Diretoria",
                "ordering": ["cargo__ordem_hierarquica", "associado__nome"],
                "unique_together": {("associado", "cargo", "data_inicio")},
            },
        ),
        migrations.CreateModel(
            name="AtaReuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Reunião"),
                ),
                (
                    "tipo_reuniao",
                    models.CharField(
                        choices=[
                            ("ordinaria", "Reunião Ordinária"),
                            ("extraordinaria", "Reunião Extraordinária"),
                            ("emergencia", "Reunião de Emergência"),
                            ("especial", "Reunião Especial"),
                        ],
                        default="ordinaria",
                        max_length=20,
                        verbose_name="Tipo de Reunião",
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateTimeField(verbose_name="Data e Hora da Reunião"),
                ),
                (
                    "local",
                    models.CharField(max_length=200, verbose_name="Local da Reunião"),
                ),
                ("pauta", models.TextField(verbose_name="Pauta da Reunião")),
                ("deliberacoes", models.TextField(verbose_name="Deliberações")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "arquivo_ata",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="diretoria/atas/",
                        verbose_name="Arquivo da Ata",
                    ),
                ),
                (
                    "aprovada",
                    models.BooleanField(default=False, verbose_name="Ata Aprovada"),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "membros_ausentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reunioes_ausente",
                        to="diretoria.membrodiretoria",
                        verbose_name="Membros Ausentes",
                    ),
                ),
                (
                    "membros_presentes",
                    models.ManyToManyField(
                        related_name="reunioes_presente",
                        to="diretoria.membrodiretoria",
                        verbose_name="Membros Presentes",
                    ),
                ),
                (
                    "presidente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunioes_presididas",
                        to="diretoria.membrodiretoria",
                        verbose_name="Presidente da Reunião",
                    ),
                ),
                (
                    "secretario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunioes_secretariadas",
                        to="diretoria.membrodiretoria",
                        verbose_name="Secretário da Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata de Reunião",
                "verbose_name_plural": "Atas de Reunião",
                "ordering": ["-data_reuniao"],
            },
        ),
        migrations.CreateModel(
            name="ResolucaoDiretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número da Resolução"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título da Resolução"
                    ),
                ),
                ("ementa", models.TextField(verbose_name="Ementa")),
                ("texto_integral", models.TextField(verbose_name="Texto Integral")),
                ("data_resolucao", models.DateField(verbose_name="Data da Resolução")),
                (
                    "data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "data_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vigência"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aprovada", "Aprovada"),
                            ("revogada", "Revogada"),
                            ("suspensa", "Suspensa"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arquivo_resolucao",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="diretoria/resolucoes/",
                        verbose_name="Arquivo da Resolução",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ata_reuniao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolucoes",
                        to="diretoria.atareuniao",
                        verbose_name="Ata de Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolução da Diretoria",
                "verbose_name_plural": "Resoluções da Diretoria",
                "ordering": ["-data_resolucao", "-numero"],
            },
        ),
    ]
