# Generated by Django 5.0.2 on 2025-09-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateAta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Template"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição do Template"),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="HTML do template com placeholders como [TITULO], [DATA], etc.",
                        verbose_name="Conteúdo do Template",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Template Ativo"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Ata",
                "verbose_name_plural": "Templates de Ata",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="atareuniao",
            name="conteudo_completo",
            field=models.TextField(
                blank=True,
                help_text="Editor único para toda a ata com modelos prontos",
                verbose_name="Conteúdo Completo da Ata",
            ),
        ),
    ]
