# Generated by Django 5.0.2 on 2025-09-05 01:06

import diretoria.models_ata_simples
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0002_templateata_atareuniao_conteudo_completo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaSimples",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Ata"),
                ),
                (
                    "titulo_slug",
                    models.SlugField(
                        blank=True, max_length=200, verbose_name="Slug do Título"
                    ),
                ),
                (
                    "tipo_reuniao",
                    models.CharField(
                        choices=[
                            ("ordinaria", "Reunião Ordinária"),
                            ("extraordinaria", "Reunião Extraordinária"),
                            ("emergencia", "Reunião de Emergência"),
                            ("especial", "Reunião Especial"),
                        ],
                        default="ordinaria",
                        max_length=20,
                        verbose_name="Tipo de Reunião",
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Hora da Reunião",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        default="Sede da ABMEPI",
                        max_length=200,
                        verbose_name="Local da Reunião",
                    ),
                ),
                (
                    "presidente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Presidente"
                    ),
                ),
                (
                    "secretario",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Secretário"
                    ),
                ),
                (
                    "membros_presentes",
                    models.TextField(
                        blank=True,
                        help_text="Lista os membros presentes, um por linha",
                        verbose_name="Membros Presentes",
                    ),
                ),
                (
                    "membros_ausentes",
                    models.TextField(
                        blank=True,
                        help_text="Lista os membros ausentes, um por linha",
                        verbose_name="Membros Ausentes",
                    ),
                ),
                (
                    "pauta",
                    models.TextField(
                        blank=True,
                        help_text="Itens da pauta da reunião",
                        verbose_name="Pauta",
                    ),
                ),
                (
                    "deliberacoes",
                    models.TextField(
                        blank=True,
                        help_text="Decisões tomadas na reunião",
                        verbose_name="Deliberações",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações adicionais",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "conteudo_html",
                    models.TextField(
                        blank=True,
                        help_text="Conteúdo HTML da ata",
                        verbose_name="Conteúdo HTML",
                    ),
                ),
                (
                    "arquivo_html",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=diretoria.models_ata_simples.upload_ata_path,
                        verbose_name="Arquivo HTML",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("finalizada", "Finalizada"),
                            ("assinada", "Assinada"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata Simples",
                "verbose_name_plural": "Atas Simples",
                "ordering": ["-data_reuniao"],
            },
        ),
    ]
