# Generated by Django 5.0.2 on 2025-09-05 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0003_atasimples"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloAtaPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição do Modelo"),
                ),
                (
                    "conteudo_html",
                    models.TextField(verbose_name="Conteúdo HTML do Modelo"),
                ),
                (
                    "titulo_original",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Título da Ata Original",
                    ),
                ),
                (
                    "tipo_reuniao",
                    models.CharField(
                        choices=[
                            ("ordinaria", "Reunião Ordinária"),
                            ("extraordinaria", "Reunião Extraordinária"),
                            ("emergencia", "Reunião de Emergência"),
                            ("especial", "Reunião Especial"),
                        ],
                        default="ordinaria",
                        max_length=20,
                        verbose_name="Tipo de Reunião",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        default="geral",
                        help_text="Ex: reunião ordinária, assembleia, emergência",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Modelo Ativo"),
                ),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, outros usuários podem usar este modelo",
                        verbose_name="Modelo Público",
                    ),
                ),
                (
                    "vezes_usado",
                    models.PositiveIntegerField(default=0, verbose_name="Vezes Usado"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_ata_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata Personalizado",
                "verbose_name_plural": "Modelos de Ata Personalizados",
                "ordering": ["-data_atualizacao", "nome"],
            },
        ),
    ]
