# Generated by Django 5.0.2 on 2025-09-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0004_modeloatapersonalizado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloAta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição do Modelo"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("ordinaria", "Reunião Ordinária"),
                            ("extraordinaria", "Reunião Extraordinária"),
                            ("emergencia", "Emergência"),
                            ("assembleia", "Assembleia"),
                        ],
                        default="geral",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo do Modelo")),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, outros usuários podem usar este modelo",
                        verbose_name="Modelo Público",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Modelo Ativo"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata",
                "verbose_name_plural": "Modelos de Ata",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
