# Generated by Django 5.0.2 on 2025-09-05 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0005_modeloata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloAtaUnificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificador do modelo",
                        max_length=200,
                        verbose_name="Nome do Modelo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do modelo",
                        verbose_name="Descrição do Modelo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("ordinaria", "Reunião Ordinária"),
                            ("extraordinaria", "Reunião Extraordinária"),
                            ("emergencia", "Emergência"),
                            ("assembleia", "Assembleia"),
                            ("conselho", "Conselho"),
                            ("comissao", "Comissão"),
                        ],
                        default="geral",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "tipo_conteudo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto Simples"),
                            ("html", "HTML"),
                            ("template", "Template Django"),
                        ],
                        default="texto",
                        max_length=10,
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo principal do modelo",
                        verbose_name="Conteúdo do Modelo",
                    ),
                ),
                (
                    "conteudo_html",
                    models.TextField(
                        blank=True,
                        help_text="Versão HTML do conteúdo (se aplicável)",
                        verbose_name="Conteúdo HTML",
                    ),
                ),
                (
                    "titulo_original",
                    models.CharField(
                        blank=True,
                        help_text="Título da ata que originou este modelo",
                        max_length=200,
                        verbose_name="Título da Ata Original",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separadas por vírgula para facilitar a busca",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, outros usuários podem usar este modelo",
                        verbose_name="Modelo Público",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se desmarcado, o modelo não aparecerá nas listagens",
                        verbose_name="Modelo Ativo",
                    ),
                ),
                (
                    "vezes_usado",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantas vezes este modelo foi utilizado",
                        verbose_name="Vezes Usado",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "ultimo_uso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Uso"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_ata_unificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata Unificado",
                "verbose_name_plural": "Modelos de Ata Unificados",
                "ordering": ["-data_atualizacao", "nome"],
                "indexes": [
                    models.Index(
                        fields=["categoria", "ativo"],
                        name="diretoria_m_categor_b0fdba_idx",
                    ),
                    models.Index(
                        fields=["publico", "ativo"],
                        name="diretoria_m_publico_1faa2c_idx",
                    ),
                    models.Index(
                        fields=["criado_por", "ativo"],
                        name="diretoria_m_criado__c41169_idx",
                    ),
                ],
            },
        ),
    ]
