# Generated by Django 5.0.2 on 2025-09-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diretoria", "0006_add_modelo_ata_unificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="atareuniao",
            name="numero_sequencial",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número sequencial da ata por tipo de reunião",
                null=True,
                verbose_name="Número Sequencial",
            ),
        ),
    ]
