# Generated by Django 5.0.2 on 2025-09-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0013_associado_nome_mae_associado_nome_pai_and_more"),
        ("diretoria", "0008_atasimples_numero_sequencial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atareuniao",
            name="associados_ausentes",
            field=models.ManyToManyField(
                blank=True,
                related_name="atas_ausente",
                to="associados.associado",
                verbose_name="Associados Ausentes",
            ),
        ),
        migrations.AddField(
            model_name="atareuniao",
            name="associados_presentes",
            field=models.ManyToManyField(
                blank=True,
                related_name="atas_presente",
                to="associados.associado",
                verbose_name="Associados Presentes",
            ),
        ),
    ]
