# Generated by Django 5.0.2 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipomensalidade",
            options={
                "ordering": ["categoria", "nome"],
                "verbose_name": "Tipo de Mensalidade",
                "verbose_name_plural": "Tipos de Mensalidade",
            },
        ),
        migrations.AddField(
            model_name="tipomensalidade",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("mensalidade", "Mensalidade de Associado"),
                    ("outros", "Outros Recebimentos"),
                ],
                default="mensalidade",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
    ]
