# Generated by Django 5.0.2 on 2025-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_tipomensalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(verbose_name='Data e Hora do Pagamento'),
        ),
    ]
