# Generated by Django 5.0.2 on 2025-08-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_alter_pagamento_data_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensalidade",
            name="codigo_barras",
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="financeiro.tipomensalidade",
                verbose_name="Tipo de Recebimento",
            ),
        ),
    ]
