# Generated by Django 5.0.2 on 2025-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_remove_codigo_barras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipomensalidade",
            name="categoria",
            field=models.CharField(
                choices=[("mensalidade", "Mensalidade de Associado")],
                default="mensalidade",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
    ]
