# Generated by Django 5.0.2 on 2025-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_alter_tipomensalidade_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoCobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da configuração (ex: Configuração Padrão)",
                        max_length=100,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Configuração ativa para uso"
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        help_text="Chave PIX para pagamento", max_length=100
                    ),
                ),
                (
                    "titular",
                    models.CharField(
                        help_text="Nome do titular da conta", max_length=100
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        help_text="Nome do banco ou instituição", max_length=100
                    ),
                ),
                (
                    "mensagem_linha1",
                    models.CharField(
                        default="Pague Suas mensalidade na sede da",
                        help_text="Primeira linha da mensagem",
                        max_length=100,
                    ),
                ),
                (
                    "mensagem_linha2",
                    models.CharField(
                        default="associação ou pelo QRcode e mande o",
                        help_text="Segunda linha da mensagem",
                        max_length=100,
                    ),
                ),
                (
                    "mensagem_linha3",
                    models.CharField(
                        default="comprovante para",
                        help_text="Terceira linha da mensagem",
                        max_length=100,
                    ),
                ),
                (
                    "telefone_comprovante",
                    models.CharField(
                        default="86 988197790",
                        help_text="Telefone para envio do comprovante",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code_ativo",
                    models.BooleanField(
                        default=True, help_text="Exibir QR Code no carnê"
                    ),
                ),
                (
                    "qr_code_tamanho",
                    models.IntegerField(
                        default=15, help_text="Tamanho do QR Code em mm"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Cobrança",
                "verbose_name_plural": "Configurações de Cobrança",
                "ordering": ["-ativo", "-data_criacao"],
            },
        ),
    ]
