# Generated by Django 5.0.2 on 2025-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_configuracaocobranca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaocobranca",
            options={
                "ordering": ["-ativo", "-data_criacao"],
                "verbose_name": "Configuração de Cobrança",
                "verbose_name_plural": "Configuração de Cobrança",
            },
        ),
        migrations.RemoveField(
            model_name="configuracaocobranca",
            name="mensagem_linha1",
        ),
        migrations.RemoveField(
            model_name="configuracaocobranca",
            name="mensagem_linha2",
        ),
        migrations.RemoveField(
            model_name="configuracaocobranca",
            name="mensagem_linha3",
        ),
        migrations.AddField(
            model_name="configuracaocobranca",
            name="mensagem",
            field=models.TextField(
                default="Pague suas mensalidades na sede da associação ou pelo QR Code e envie o comprovante para o telefone informado",
                help_text="Mensagem personalizada para o carnê",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="configuracaocobranca",
            name="qr_code_imagem",
            field=models.ImageField(
                blank=True,
                help_text="Imagem do QR Code (PNG, JPG)",
                null=True,
                upload_to="qr_codes/",
            ),
        ),
    ]
