# Generated by Django 5.0.2 on 2025-08-18 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                ("tipo", models.CharField(max_length=20)),
                ("prioridade", models.CharField(default="normal", max_length=20)),
                ("data_publicacao", models.DateTimeField(auto_now_add=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("destinatarios", models.TextField(blank=True)),
                ("enviar_email", models.BooleanField(default=False)),
                ("enviar_sms", models.BooleanField(default=False)),
                (
                    "arquivos_anexados",
                    models.FileField(
                        blank=True, null=True, upload_to="administrativo/comunicados/"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicado",
                "verbose_name_plural": "Comunicados",
                "ordering": ["-data_publicacao"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("tipo", models.CharField(max_length=20)),
                ("status", models.CharField(default="agendado", max_length=20)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("local", models.CharField(max_length=200)),
                ("endereco", models.TextField(blank=True)),
                (
                    "capacidade_maxima",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "valor_inscricao",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="administrativo/eventos/"
                    ),
                ),
                (
                    "arquivos_anexados",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="administrativo/eventos/arquivos/",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_presenca",
                        to="administrativo.evento",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Presenca",
                "verbose_name_plural": "Listas de Presenca",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="ParticipanteEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("associado", models.CharField(max_length=200)),
                ("status", models.CharField(default="pendente", max_length=20)),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                ("data_confirmacao", models.DateTimeField(blank=True, null=True)),
                ("data_presenca", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="administrativo.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante do Evento",
                "verbose_name_plural": "Participantes dos Eventos",
                "ordering": ["data_inscricao"],
            },
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("associado", models.CharField(max_length=200)),
                ("presente", models.BooleanField(default=False)),
                ("horario_chegada", models.TimeField(blank=True, null=True)),
                ("horario_saida", models.TimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "lista_presenca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="administrativo.listapresenca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presenca",
                "verbose_name_plural": "Presencas",
                "ordering": ["associado"],
            },
        ),
    ]
