# Generated by Django 5.0.2 on 2025-08-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0001_initial"),
        ("associados", "0005_alter_associado_posto_graduacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participanteevento",
            name="associado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participacoes_evento",
                to="associados.associado",
            ),
        ),
        migrations.AlterField(
            model_name="presenca",
            name="associado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presencas",
                to="associados.associado",
            ),
        ),
    ]
