# Generated by Django 5.0.2 on 2025-08-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0002_alter_participanteevento_associado_and_more"),
        ("assejus", "0004_remove_relatoriojuridico_arquivo_and_more"),
        ("associados", "0005_alter_associado_posto_graduacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="advogados_especificos",
            field=models.ManyToManyField(
                blank=True, to="assejus.advogado", verbose_name="Advogados Específicos"
            ),
        ),
        migrations.AddField(
            model_name="comunicado",
            name="associados_especificos",
            field=models.ManyToManyField(
                blank=True,
                to="associados.associado",
                verbose_name="Associados Específicos",
            ),
        ),
        migrations.AddField(
            model_name="comunicado",
            name="tipo_destinatarios",
            field=models.CharField(
                choices=[
                    ("todos", "Todos os Associados e Advogados"),
                    ("associados", "Apenas Associados"),
                    ("advogados", "Apenas Advogados"),
                    ("especificos", "Seleção Específica"),
                ],
                default="todos",
                max_length=20,
                verbose_name="Tipo de Destinatários",
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="destinatarios",
            field=models.TextField(
                blank=True, verbose_name="Destinatários Personalizados"
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("informacao", "Informação"),
                    ("aviso", "Aviso"),
                    ("lembrete", "Lembrete"),
                    ("urgencia", "Urgência"),
                    ("evento", "Evento"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
