# Generated by Django 5.0.2 on 2025-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0003_comunicado_advogados_especificos_and_more"),
        ("psicologia", "0011_fix_cpf_field_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="enviar_notificacao",
            field=models.BooleanField(default=False, verbose_name="Enviar Notificação"),
        ),
        migrations.AddField(
            model_name="comunicado",
            name="psicologos_especificos",
            field=models.ManyToManyField(
                blank=True,
                to="psicologia.psicologo",
                verbose_name="Psicólogos Específicos",
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="tipo_destinatarios",
            field=models.CharField(
                choices=[
                    ("todos", "Todos os Associados, Advogados e Psicólogos"),
                    ("associados", "Apenas Associados"),
                    ("advogados", "Apenas Advogados"),
                    ("psicologos", "Apenas Psicólogos"),
                    ("especificos", "Seleção Específica"),
                ],
                default="todos",
                max_length=20,
                verbose_name="Tipo de Destinatários",
            ),
        ),
    ]
